on:
  push:
    branches:
      - main
      - surface

name: Release Box

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: print-name
        run: |
          echo "${{ env.REPO_NAME }}"